[tool.poetry]
name = "piano-transcriber"
version = "0.0.1"
description = ""
authors = ["Your Name <you@example.com>"]
license = "AGPL"
readme = "README.md"
packages=[{include = "src"}]

[tool.poetry.dependencies]
python = "3.12.7"
mido = "^1.3.2"
numpy = "^1.26.4"
onnxruntime = "1.18"

[tool.poetry.group.dev.dependencies]
torch = "^2.3.0"
onnx = "^1.16.1"
onnxconverter-common = "^1.14.0"
torchlibrosa = "^0.1.0"
ruff = "^0.8.1"
pytest = "^8.3.4"
syrupy = "^4.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
