name: PR

on:
  pull_request:
    branches: [main]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo at latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Setup poetry
        uses: snok/install-poetry@v1
        with:
          version: latest

      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release

      - name: Get base and head commits for `nx affected`
        uses: nrwl/nx-set-shas@v4.1.2
        with:
          main-branch-name: main

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run affected tests
        run: pnpm test
